### ISSUE TITLE
Reference to networkD3???

### ISSUE THREAD

**Issue by pommedeterresautee** [rich-iannone/DiagrammeR#17]
In file https://github.com/rich-iannone/DiagrammeR/blob/ad4221579fdb5458b47c8b2a278f899a3ced46a0/R/DiagrammeR.R#L131 there is a reference to networkD3. I may have missed something big but it seems to me that it is another library and DiagrammeR is center on Mermaid, isn't it?

**Comment by timelyportfolio** [comment]
Good catch, `DiagrammeR` as of now is focused entirely on `mermaid.js`.  Assuming I copied/pasted that bit, since `scaffoldWidget` creates the skeleton for these `Shiny` rendering functions.

@rich-iannone can confirm, but idea behind DiagrammeR is not full-featured network graphs but an extremely simple way to express diagrams and have them render in the relevant context.  I am sure that `networkD3` or future widgets will offer more interactive and fully-featured network graphs, but they will probably pay the price of complexity.  My basic premise is that the features should primarily be implemented on the `JavaScript` side and the `htmlwidget` should focus on bridging R contexts, calculations, paradigms, and data structures to these features in the `JavaScript` library.

@rich-iannone, want me to wait to change since in middle of CRAN submission?  I'll submit a pull.  Feel free to disregard.

**Comment by rich-iannone** [comment]
Thanks for bringing this up, @pommedeterresautee and thanks for the pull request, @timelyportfolio!
