### ISSUE TITLE
add_node() no longer supports `node` parameter

### ISSUE THREAD

**Issue by gothub** [rich-iannone/DiagrammeR#205]
Commit e70825265333616c5d2a0f759a4b2ca96396737f removed the `node` parameter
from `add_node()`, which allowed defining the node id for a new node. WIth the 0.9
release, is there another way to use user defined node ids instead of the ids generated
automatically by the package

It was really convenient to be able to specify the id of a node, as I'm using this package to display 
a DAG structure that assigns ids to each node. If I have to rely on the ids that `add_node()` assigns to a node, then I have to have a lookup table between the DAG node ids and the DiagrammeR node ids. 

Please add back in the ability to assign a user defined id to a node.

**Comment by rich-iannone** [comment]
You can get the same sort of functionality back for your application by assigning the name to the `label` attribute. The label gets displayed by default when rendering the graph. It's also possible to, on a node-by-node basis, to specify which attributes values get displayed by using the `set_node_attr_to_display()` function.

If you could, provide a relevant code sample of your application and I can provide a working alternative.

**Comment by gothub** [comment]
@rich-iannone This issue doesn't involve the label of a node, but rather the ability to specify
the node id when a node or link is added. My use case is that I have a DAG that I've build in R, 
and each node in the DAG has a node id, in my case a UUID. When I build the DiagrammeR graph
I used to be able to assign each node in the DiagrammeR graph to have the corresponding value from my R DAG. V 0.9.0 doesn't allow the user to specify node id values, so in my case, I'd have to keep a lookup table between the values DiagrammeR assigns to a node when it is created, and the 
corresponding uuid for my DAG node, so that I know what values to specify when adding links, querying the graph, etc.

**Comment by rich-iannone** [comment]
@gothub 

Here's an example that may help:

```r
# Create graph
graph <-
  create_graph() %>%
  add_node(label = "name_1") %>%
  add_node(label = "name_2") %>%
  add_edge(
    from = "name_1",
    to = "name_2",
    use_labels = TRUE) %>%
  select_edges(
    from = get_node_ids(., conditions = "label == 'name_1'"),
    to = get_node_ids(., conditions = "label == 'name_2'")) %>%
  set_edge_attrs_ws("color", "green") %>%
  clear_selection() %>%
  select_nodes(conditions = "label == 'name_1'") %>%
  set_node_attrs_ws("fillcolor", "gray5") %>%
  clear_selection() %>%
  select_nodes(conditions = mk_cond("label", "==", "name_2")) %>%
  set_node_attrs_ws("fillcolor", "gray85") %>%
  clear_selection()

# View the graph
render_graph(graph)
``` 

<img width="494" alt="screen shot 2017-01-18 at 10 53 38 pm" src="https://cloud.githubusercontent.com/assets/5612024/22096538/03784fde-ddd1-11e6-9b78-6f38c00b1942.png">

Here you can add an edge by specifying the label names (with the `use_labels = TRUE` option in the `add_edge()` function). You can select edges by getting the node ID values for the `from` and `to` arguments with a single condition (since `label` values throughout the graph are unique here). You can also use the `mk_cond()` helper function with the `conditions` argument to have better control over the conditions (e.g., you can add variables, functions, etc.).

I hope this is helpful. Let me know if there are any questions about this.

**Comment by gothub** [comment]
@rich-iannone I guess I haven't made my use case clear. I'd like to specify the id of a node, not use the label as the id (my labels might not be unique). The ability to specify the id of a vertex of a graph is available in graphing packages in other languages (e.g. Java), and was available in DiagrammeR before v0.9.  I'm a bit surprised that other users aren't building graphs in this way. I'll continue to use
my external mapping of my DAG ids to DiagrammeR assigned ids.

I'm really glad that this package is available, thanks for proposing alternative solutions.

**Comment by janvydra** [comment]
I have the same problem and it is not solved by using labels instead of ID's. Labels are not necessarily unique and/or contain generated text - in my case number of cases in a given group for example. If I use labels to identify nodes, these labels cannot contain dynamically generated text.  So I must say that I really miss the possibility to assign ID's to nodes. Its similar to HTML where elements have separate names, labels and ID'đ and all of these are useful.

Thanks
Jan

**Comment by rich-iannone** [comment]
@janvydra

Could you send a small code example of where the pain point occurs? Perhaps we could resolve this through some discussion upon a closer look at your application.

**Comment by janvydra** [comment]
Hello, thank you for the reply, I figured out how to solve it - now I use add_node_df which lets me add any attributes including my custom IDs and retrieve the nodes through get_node_ids("ID == 'whateverid'").

Maybe it would be useful if was possible to pass arbitrary attributes to add_node() (for example ID = "blbla", data = 33.5) so that one would not have to go through dataframes.

Thanks.
Jan

**Comment by rich-iannone** [comment]
What you’re describing is possible currently in the dev version of the package. Functions that create nodes and/or edges have arguments specifically for adding in arbitrary data.

This is split between those attributes that are aesthetics-based and attributes that contain arbitrary data values. Use the `node_aes()`, `node_data()`, `edge_aes()`, and `edge_data()` functions work within their namesake arguments to help bind attribute values to the newly-created nodes/edges. 

Some examples are in the in-package documentation (try `help(create_path)` for a complete set of examples).

Let me know if this helps and please provide some advice or comments in a separate issue for this.

**Comment by arazdow** [comment]
I have the same issue, but would be happy with being able to receive the ID of the new add_node() node.  For example, if I want to add an edge FROM the new node, I need to know the ID of the new node.  Is there a way to get that information?  For example:
get_id_of_newest_node()
