### ISSUE TITLE
Adding gaps or borders 

### ISSUE THREAD

**Issue by skanskan** [rich-iannone/DiagrammeR#253]
How can I add a white border around every node?
And around edge labels?
The first will let to force the arrows not to touch the node.
The second will serve to avoid overlappings with edges.
And how can I create a gap when two edges cross each other?
![ogovh](https://user-images.githubusercontent.com/4120283/32074372-769ec4c0-ba99-11e7-910e-fc391a22236c.png)

https://stackoverflow.com/questions/46811267/how-to-minimize-the-number-of-edge-crossings-with-diagrammer-r

**Comment by rich-iannone** [comment]
There is currently no way to do this since there is only the possibility of a single border. Peripheries might be an idea, but all peripheries are coloured the same as the node border color. Edge crossings also can't be done like in the drawing (would need to have a secondary line with a different penwidth that's drawn below).

**Comment by mike-lawrence** [comment]
> There is currently no way to do this since there is only the possibility of a single border.

@rich-iannone Sorry to resurrect an old issue, but how is a single border around the entire diagram achieved?
