### ISSUE TITLE
2-digit footnote doesn't work

### ISSUE THREAD

**Issue by jpinero** [rich-iannone/DiagrammeR#378]
hi, it is still the same issue that has not been solved
https://github.com/rich-iannone/DiagrammeR/issues/188 
thanks!

**Comment by wildingm** [comment]
Hi, I've also come across this issue today, but this _was_ working recently. I'm currently on 3.6.1 version of R.

When I run the code it replaces all nodes with @@1x with the output of footnote [1]. A test flowchart (below) produces a flowchart where nodes @@10 through @@19 all include the output from footnote [1] (with an addition to make them unique), node @@20 includes the output from footnote [2].

```
flowchart <- grViz("digraph flowchart {

  @@1 -> @@2
  @@2 -> @@3
  @@3 -> @@4
  @@4 -> @@5
  @@5 -> @@6
  @@6 -> @@7
  @@7 -> @@8
  @@8 -> @@9
  @@9 -> @@10
  @@10 -> @@11
  @@11 -> @@12
  @@12 -> @@13
  @@13 -> @@14
  @@14 -> @@15
  @@15 -> @@16
  @@16 -> @@17
  @@17 -> @@18
  @@18 -> @@19
  @@19 -> @@20
  
}
  
  [1]: 'One'
  [2]: 'Two'
  [3]: 'Three'
  [4]: 'Four'
  [5]: 'Five'
  [6]: 'Six'  
  [7]: 'Seven'  
  [8]: 'Eight'  
  [9]: 'Nine'  
  [10]: 'Ten'
  [11]: 'Eleven'
  [12]: 'Twelve'
  [13]: 'Thirteen'
  [14]: 'Fourteen'
  [15]: 'Fifteen'
  [16]: 'Sixteen'
  [17]: 'Seventeen'
  [18]: 'Eighteen'
  [19]: 'Nineteen'
  [20]: 'Twenty'
  
")  

flowchart
```

It appears that the package is only parsing the first digit of the node number and not including any subsequent digits where they are present (i.e. it is reading @@10 and @@18 as @@1)

Hope this helps identify a fix.

**Comment by datakeen** [comment]
I also encountered this issue recently. I have a code that has 13 nodes, each with a separate label. I actually created it around a year ago (I am not sure exactly which version of R and DiagrammeR package was that), and the code was working fine then. Just recently, I modified the graph code a bit and encountered this bug. And when I run the old code (made one year ago), this error appears in that graph as well, which was previously working fine. It seems that the bug finds its way in recent R/DiagrammeR versions. 
My workaround to escape from this package is that instead of substitution, write the label directly in front of node statement for all nodes or at least for nodes that require substitution entries `greater` than 9.
```
grViz("
digraph dot {

graph [layout = dot]

node [shape = circle,
      style = filled,
      color = grey]

node [fillcolor = red]
a[label='@@1']

node [fillcolor = green]
b [label='@@2']
c [label='@@3']
d [label='@@4']

node [fillcolor = orange]
e [label='@@5']
f [label='@@6']
g [label='@@7']
h [label='@@8']
i [label='@@9']
j [label='History \\n Globe ']
k [label='Debug']
l [label='Thumb \\n Plot ']
n [label='@@9']
o [label='@@8']
p [label='@@7']
q [label='@@6']
r [label='@@5']
s [label='@@4']
t [label='@@3']
u [label='@@2']

edge [color = grey]
a -> {b c d}
b -> {e f g h i j}
c -> {k l n o p}
d -> {q r s t u}
}
 [1]: 'Some meaningless \\n node labels'     
 [2]: 'Help'  
 [3]: 'Source'  
 [4]: 'Save'    
 [5]: 'Code'        
 [6]: 'View'        
 [7]: 'RSTudio'     
 [8]: 'Keyboard'  
 [9]: 'Finger'  
 [10]: 'History \\n Globe '    
 [11]: 'Debug'        
 [12]: 'Thumb \\n Plot '
      ")

```

**Comment by anddis** [comment]
Same exact issue here. To me, it appeared with v1.0.5.

**Comment by allenzhuaz** [comment]
I have the same issue, in practice, it is easily to have more than 9 footnotes.
