### ISSUE TITLE
There is no example in the documentation

### ISSUE THREAD

**Issue by pommedeterresautee** [rich-iannone/DiagrammeR#52]
The README is beautiful but in R documentation there is no example for graphviz

**Comment by rich-iannone** [comment]
@pommedeterresautee the R documentation is definitely far behind. I'll update that tonight!

**Comment by pommedeterresautee** [comment]
Great, I think you can add any link as a Vignette. Why not add the video as a Vignette? It shows code. Just an idea.

**Comment by rich-iannone** [comment]
@pommedeterresautee that's a great idea. I think I'll do that!

**Comment by rich-iannone** [comment]
I'm going to overhaul the vignettes once the documentation on the website is adequate. The plan:

1. Get the documentation on https://rich-iannone.github.io/DiagrammeR/docs.html in good shape, so that everything is clear and that all options are explained.

2. Remove the documentation from the GitHub README.md, leaving only the features/basics and a link to the DiagrammeR `gh-pages` site.

3. Create PDF vignettes based on the documentation at the DiagrammeR `gh-pages` site

I'll open separate issues for these. For now, I'll close this issue.
